import type { Metadata } from "next";
import { PageHeader } from "@/components/layout/page-header";
import { SearchBar } from "@/components/ui/search-bar";
import { StatusBadge } from "@/components/ui/status-badge";
import { Pagination } from "@/components/ui/pagination";
import { adminApi, Payment, Meta } from "@/services/admin.service";
import { FormSelect } from "@/components/ui/form-select";
export const metadata: Metadata={title:"Payments"};
const date=(v:string)=>new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(v));
export default async function Payments({searchParams}:{searchParams:Promise<{search?:string;status?:string;page?:string}>}){const q=await searchParams;const params=new URLSearchParams({search:q.search??"",status:q.status??"all",page:q.page??"1"});const data=await adminApi<{items:Payment[];meta:Meta}>(`/v1/admin/payments?${params}`);return <><PageHeader title="Payments" description="Track checkout attempts, confirmations, and successful license fulfillment."/><div className="card overflow-hidden"><SearchBar value={q.search} placeholder="Search email or reference…"><FormSelect name="status" defaultValue={q.status??"all"} options={[{value:"all",label:"All statuses"},{value:"paid",label:"Paid"},{value:"pending",label:"Pending"},{value:"creating",label:"Creating"}]}/></SearchBar><div className="table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Plan</th><th>Amount</th><th>Created</th><th>Status</th></tr></thead><tbody>{data.items.map(p=><tr key={p.id}><td className="max-w-40 truncate font-mono text-[11px] text-gray-500" title={p.reference_id}>{p.reference_id}</td><td className="font-medium">{p.customer_email}</td><td className="capitalize">{p.plan.replace("_"," ")}</td><td className="font-semibold">${p.amount} <span className="text-[10px] text-gray-400">{p.currency}</span></td><td>{date(p.created_at)}</td><td><StatusBadge status={p.status}/></td></tr>)}{!data.items.length&&<tr><td colSpan={6} className="py-14 text-center text-gray-400">No payments match your filters.</td></tr>}</tbody></table></div><Pagination meta={data.meta} query={{search:q.search,status:q.status}}/></div></>}
